Setup infra
SE-Row-1/nus-secondhand-market pull request #32
Opened 2024-10-12 13:48 UTC by z1yoon

2024-10-13 03:01 UTC, mrcaidev reviewed
I guess `services/item/mongodb` and `services/wishlist/mongodb` should not be committed onto GitHub.

2024-10-13 03:42 UTC, mrcaidev requested changes
Thanks for all your hard work! I proposed some changes and questions, and hope you could try to resolve them.

2024-10-13 03:42 UTC, mrcaidev commented on .github/workflows/provision-destroy.yaml
> +      - setup-infra
This workflow is seemingly meant to be manually triggered. Do we need to have it also triggered on "push to setup-infra"?

2024-10-13 03:42 UTC, mrcaidev commented on .github/workflows/provision-destroy.yaml
>          required: true
If `required=true`, there is no need to provide a `default`. I suppose this could also be `required=false`, because when an admin wants to `destroy`, he/she can surely omit this option.
```suggestion
        required: false
```

2024-10-13 03:42 UTC, mrcaidev commented on .github/workflows/provision-destroy.yaml
>            path: terraform/*.txt
Is this safe? Only we can access this artifact, or every public visitor to this repository also can?

2024-10-13 03:42 UTC, mrcaidev commented on .github/workflows/provision-destroy.yaml
> +    if: ${{ github.event.inputs.destroy == 'true' }}
```suggestion
    if: ${{ github.event.inputs.destroy == true }}
```

2024-10-13 03:42 UTC, mrcaidev commented on .github/workflows/provision-destroy.yaml
After reading through this workflow, I feel like provision job and destroy job are largely unrelated to each other, and I could hardly imagine a situation where you would like to provision & destroy at the same time.

If so, do you think it's a good idea to separate them into 2 workflows?

2024-10-13 03:42 UTC, mrcaidev commented on .github/workflows/gitops-workflow.yaml
> +name: GitOps Workflow
Forgive me being a little picky here - we can remove the word "Workflow" in the name here and the file name, as it's already undoubtedly a workflow.

This is like setting my nickname to "CAI YUWANG The Human", but everybody surely knows I'm a human.
```suggestion
name: GitOps
```

2024-10-13 03:42 UTC, mrcaidev commented on helm/values.yaml
> +      - name: whishlist
Typo here.

```suggestion
      - name: wishlist
```

2024-10-13 03:42 UTC, mrcaidev commented on docker-compose.dev.yaml
> +    environment:
Item service needs a lot more env vars, such as `JWT_SECRET_KEY`, `S3_BUCKET_NAME`, etc. And `MONGO_URL` should be `MONGO_URI`.

It is clearly documented in `services/item/.env.example`.

2024-10-13 03:42 UTC, mrcaidev commented on docker-compose.dev.yaml
> +    depends_on:
This should depend on all other services, not just web and account?

2024-10-13 03:42 UTC, mrcaidev commented on docker-compose.dev.yaml
> +version: '3.8'
`version` is obsolete and should not be further used. See [Docker Compose file reference](https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-obsolete).
```suggestion
```

2024-10-13 03:42 UTC, mrcaidev commented on docker-compose.dev.yaml
> +      - ./services/item/mongodb:/data/db
Rather than mounting `/data/db` to host machine's files, we should mount `/docker-entrypoint-initdb.d` to `./services/item/database/dev`
```suggestion
      - ./services/item/database/dev:/docker-entrypoint-initdb.d
```

2024-10-13 03:42 UTC, mrcaidev commented on docker-compose.dev.yaml
> +      - ./services/wishlist/mongodb:/data/db
This goes the same.
```suggestion
      - ./services/wishlist/database:/docker-entrypoint-initdb.d
```

2024-10-13 03:42 UTC, mrcaidev commented on docker-compose.dev.yaml
> +      - 8083:8083
If you want to make item service listen on `8083`, you should set an env var `PORT=8083`. Without this `PORT` env var, item service defaults to listening on `3000`.

2024-10-13 03:42 UTC, mrcaidev commented on docker-compose.dev.yaml
>        - postgres
Account service also depends on `rabbitmq`, but maybe yuanfan has not yet gone that far. Anyway, in the future, it's gonna be dependent on `rabbitmq`.
```suggestion
      - postgres
      - rabbitmq
```

2024-10-13 07:21 UTC, z1yoon commented on .github/workflows/provision-destroy.yaml
>          required: true
But I want to leave option `required: true` to make sure admin know what they are doing

2024-10-13 07:22 UTC, z1yoon commented on .github/workflows/provision-destroy.yaml
>            path: terraform/*.txt
oh yeah you right. i need to change it to upload to s3

2024-10-13 07:39 UTC, z1yoon commented on .github/workflows/provision-destroy.yaml
Yeap you right that's better ~!!

2024-10-13 08:14 UTC, mrcaidev requested changes
All modifications are correct. But there are still some conversations that remains unresolved. If you have different opinions about them, I would also love to hear.

2024-10-13 15:05 UTC, z1yoon commented on docker-compose.dev.yaml
> +    environment:
Question ~!
1. https://stackoverflow.com/questions/176264/what-is-the-difference-between-a-uri-a-url-and-a-urn
I searched it to make sure why i cannot use mong_url but seems i also can say url for it. Is there any specific reason mongo_url need to be uri? 
2. Can i use env_file to inject services env but only for app services not db, rabbitmq containers

2024-10-14 01:14 UTC, mrcaidev commented on docker-compose.dev.yaml
> +    environment:
## Q1

It is not quite about the difference between URL/URI. I also think the URI to mongo server is a URL as well.

But the important thing is, my item service is declaring that it wants an env var called `MONGO_URI`. You can surely name it as `MONGO_URL` in the global `.env` file, but when passing it to the item container, it still needs to be mapped back to `MONGO_URI`, or otherwise item container can't find what it really wants.

But surely I can also change all the references to `MONGO_URI` in services/item to `MONGO_URL`. Which do you think is better?

## Q2

I would not recommend doing so, for two reasons.

### Security

Every developer in every service can now read the env vars of all other services. They need to stay alert to not abuse or misuse other services' env vars.

It's a potential security loophole, an incentive to unpredictable bugs, and an extra mental burden for developers.

### Namespace Collision

The namespaces of global env vars is currently not clearly separated. By namespace I mean something like prefixing them with `ITEM_SERVICE`.

Currently, if item & wishlist both want to access `MONGO_URL`, they expect to find their own MongoDB, but they end up accidentally bumping into the same database.

A possible way to fix this collision issue is to add a namespace, such as `ITEM_SERVICE_MONGO_URL`, `WISHLIST_SERVICE_MONGO_URL`. Then if we directly pass `.env` file to services, all services also need to change their code to keep up with this naming change.

But again, this prefix now looks like an annoying redundancy, e.g. account service now prefixes all env vars with `ACCOUNT_SERVICE_` - This is like a login form asking for your "Human first name", "Human last name", ... Well of course I'm a human, why does it need to prefix like that?

So, IMO, the best way is to prefix env vars in the global `.env` with a namespace, but also respect each service's existing env name requirements, which means to explicitly pass every env to a service container. This needs some additional effort, but it's safer and cleaner.

You can find the documentation of my service's env requirements in their `.env.example` files. For account and wishlist, you might need to make sure with @JYForever0114 and @MrPhotato that every env is in place.

2024-10-14 02:32 UTC, z1yoon commented on docker-compose.dev.yaml
> +    environment:
Thank you for the reply~!
1. I don't mind for both. You pick and let me know then I will follow it.
2. How about we separate env files as per microservices? .env.item.gpg , .env.account.gpg so that developers have responsibility to use env inside container. Whenever new env need to be added, it will be extra burden to use it if we keep this way to control env. I suggest we create env dir or inside service dir and generate .env.service.gpg to control it. Then `run` script will always decrypt with updated gpg files without asking each other.

2024-10-14 03:47 UTC, mrcaidev commented on docker-compose.dev.yaml
> +    environment:
1. Then let's go with `MONGO_URI`.
2. Really nice solution. My suggestion for folder structure:

```
envs/
  |- account.env
  |- account.env.gpg
  |- item.env
  |- item.env.gpg
  |- ...
  +- .gitignore
services/
terraform/
```

```gitignore
# envs/.gitignore
*.env
```

2024-10-14 11:36 UTC, z1yoon commented on docker-compose.dev.yaml
> +    environment:
Added envs with gpg files with encrypt script , fixed run script to decrypt gpg files.

2024-10-14 11:57 UTC, mrcaidev approved these changes

2024-10-14 12:16 UTC, merged