Nshm 110 comprehensive account test
SE-Row-1/nus-secondhand-market pull request #39
Opened 2024-10-15 02:45 UTC by JYForever0114

merge: finish the account test

2024-10-15 07:15 UTC, mrcaidev requested changes

2024-10-15 07:15 UTC, mrcaidev commented on services/account/src/main/java/edu/nus/market/security/CookieManager.java
> +        ResponseCookie cookie = ResponseCookie.from("access_token", "")
Why is this changed? Deleting cookie seems to have nothing to do with all these extra properties like `httpOnly`, `path`, etc. Are you sure this is the correct way to delete a cookie?

2024-10-15 07:15 UTC, mrcaidev commented on services/account/src/main/java/edu/nus/market/security/JwtTokenManager.java
> +        String token = Arrays.stream(Cookie.split("; "))
This looks really primitive. I think Springboot is powerful enough to provide some built-in cookie management methods.

For example, in Next.js I can write something like:

```js
cookies().get("access_token") // This gets the token value
cookies().delete("access_token") // This deletes the token.
```

I believe Java should be even more powerful than this.

2024-10-15 07:15 UTC, mrcaidev commented on services/wishlist/src/main/java/edu/nus/market/pojo/AddLikeReq.java
Why is wishlist files added into this PR?

2024-10-16 06:50 UTC, JYForever0114 commented on services/account/src/main/java/edu/nus/market/security/CookieManager.java
> +        ResponseCookie cookie = ResponseCookie.from("access_token", "")
Because when I was writing the test case for cookie, I found that the value of access_token is set to "" actually, which I think can avoid NullPointerException. So I just change it to “” to make it more understandable.

2024-10-16 08:11 UTC, mrcaidev requested changes

2024-10-16 08:11 UTC, mrcaidev commented on services/account/src/main/java/edu/nus/market/controller/AccountController.java
>              return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(new ErrorMsg(ErrorMsgEnum.UNAUTHORIZED_ACCESS.ErrorMsg));
Not 401. Should be 403.

2024-10-16 14:58 UTC, mrcaidev approved these changes

2024-10-16 14:58 UTC, merged